# Generated by Django 5.1.3 on 2024-11-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smerg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='advisor_experiance',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='advisory_duration',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='brands',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='budget',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='client',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='duration',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='expertise',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='franchise_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='goals',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='horizon',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='interest',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='interested_city',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='interested_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='investing_experiance',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='risk',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='stage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='type',
            field=models.CharField(choices=[('business', 'Business'), ('advisor', 'Advisor'), ('franchise', 'Franchise'), ('investor', 'Investor'), ('all', 'All')], max_length=100),
        ),
        migrations.AlterField(
            model_name='preference',
            name='industries',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='price_ending',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='price_starting',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
