# Generated by Django 5.1.3 on 2024-11-08 04:38

import smerg_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smerg_app', '0002_preference_advisor_experiance_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', smerg_app.models.CustomUserManager()),
            ],
        ),
    ]
