# Generated by Django 5.0.6 on 2024-11-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smerg_app', '0003_alter_userprofile_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleprofiles',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
