# Generated by Django 5.0.6 on 2024-11-09 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smerg_app', '0004_saleprofiles_verified'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set(),
        ),
    ]
